### ISSUE TITLE
static files

### ISSUE THREAD

**Issue by Wambug** [ehmatthes/pcc_2e#15]
[customer_management_app.zip](https://github.com/ehmatthes/pcc_2e/files/5002546/customer_management_app.zip)
I've been working on this project for sometime following a tutorial so this is the link to the website: https://stephen-crm.herokuapp.com/ so when it comes to the user uploading his/her profile its not working can you please help me

**Comment by ehmatthes** [comment]
Hi @Wambug. I help people with issues in the Python Crash Course projects because I know those projects well, so I can jump in and help people in a reasonable timeframe. But I don't have time to dig into people's individual projects.

I do recommend people ask about other projects at [r/django](https://www.reddit.com/r/django/) or the [django forum](https://forum.djangoproject.com).
